### ISSUE TITLE
Update Claims Preprocessing

### ISSUE THREAD

**Issue by aneiderhiser** [tuva-health/claims_preprocessing#85]
Need to update the output tables from CPP to match the core data model.  Need to ensure YML files are updated to include metadata for populating thetuvaproject.com.  

<img width="557" alt="image" src="https://user-images.githubusercontent.com/11807689/223317969-f7abe120-7536-4ff8-9914-4e21d8d9cac0.png">

**Comment by aneiderhiser** [comment]
@thutuva @cocozuloaga can we close this?

**Comment by cocozuloaga** [comment]
@aneiderhiser yes, we can close this.

**Comment by aneiderhiser** [comment]
@cocozuloaga okay i'll close this.  @thutuva obviously work closely w/ coco to make sure how you're building cpp in the refactor works as intended.  Coco is focused on encounter grouper (specifically updating for ED visits) now.
